In [1]:
#importing libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv("Social_Network_Ads.csv")

In [3]:
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
#converting categorical(Gender) to numerical
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
#printing the updated dataset
dataset

User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [6]:
#re-naming the column
dataset.rename(columns={"Gender_Male":"Gender"},inplace=True)

In [7]:
#printing updated dataset
dataset

User ID  Age  EstimatedSalary  Purchased  Gender
0    15624510   19            19000          0       1
1    15810944   35            20000          0       1
2    15668575   26            43000          0       0
3    15603246   27            57000          0       0
4    15804002   19            76000          0       1
..        ...  ...              ...        ...     ...
395  15691863   46            41000          1       0
396  15706071   51            23000          1       1
397  15654296   50            20000          1       0
398  15755018   36            33000          0       1
399  15594041   49            36000          1       0

[400 rows x 5 columns]

In [8]:
#dropping the column 'User_ID'
dataset=dataset.drop("User ID",axis=1)

In [9]:
#printing the updated dataset
dataset

Age  EstimatedSalary  Purchased  Gender
0     19            19000          0       1
1     35            20000          0       1
2     26            43000          0       0
3     27            57000          0       0
4     19            76000          0       1
..   ...              ...        ...     ...
395   46            41000          1       0
396   51            23000          1       1
397   50            20000          1       0
398   36            33000          0       1
399   49            36000          1       0

[400 rows x 4 columns]

In [10]:
#printing the columns
dataset.columns

Index(['Age', 'EstimatedSalary', 'Purchased', 'Gender'], dtype='object')

In [11]:
#separating the independent and target values of dataset
independent = dataset[["Age","EstimatedSalary","Gender"]]
target = dataset[["Purchased"]]

In [12]:
#printing the independent & target
independent,target

(     Age  EstimatedSalary  Gender
 0     19            19000       1
 1     35            20000       1
 2     26            43000       0
 3     27            57000       0
 4     19            76000       1
 ..   ...              ...     ...
 395   46            41000       0
 396   51            23000       1
 397   50            20000       0
 398   36            33000       1
 399   49            36000       0
 
 [400 rows x 3 columns],
      Purchased
 0            0
 1            0
 2            0
 3            0
 4            0
 ..         ...
 395          1
 396          1
 397          1
 398          0
 399          1
 
 [400 rows x 1 columns])

In [13]:
#separating purchased and not-purchased values
dataset["Purchased"].value_counts()

0    257
1    143
Name: Purchased, dtype: int64

In [14]:
independent.shape,target.shape

((400, 3), (400, 1))

In [15]:
#separating the train and test values from dataset.
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(independent,target,test_size=0.33,random_state=42)

In [16]:
#printing the separated the train & test
print(X_train,X_test,Y_train,Y_test)

     Age  EstimatedSalary  Gender
258   58            95000       0
177   25            22000       1
119   41            59000       1
194   28            89000       1
229   42            80000       0
..   ...              ...     ...
71    24            27000       0
106   26            35000       0
270   43           133000       0
348   39            77000       1
102   32            86000       0

[268 rows x 3 columns]      Age  EstimatedSalary  Gender
209   46            22000       0
280   59            88000       0
33    28            44000       0
210   48            96000       0
93    29            28000       0
..   ...              ...     ...
332   42            65000       1
167   35            71000       0
245   51           146000       0
311   39            96000       1
145   24            89000       0

[132 rows x 3 columns]      Purchased
258          1
177          0
119          0
194          0
229          1
..         ...
71           0
106          0
2

In [17]:
X_train.shape,X_test.shape

((268, 3), (132, 3))

In [18]:
Y_train.shape,Y_test.shape

((268, 1), (132, 1))

In [19]:
#creating & training the model
from sklearn.svm import SVC
clf_model = SVC(kernel="rbf", random_state=0)
clf_model.fit(X_train,Y_train)

/home/had/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(random_state=0)

In [20]:
#printing the predicted value using actual_test value
Y_pred = clf_model.predict(X_test)

In [21]:
Y_pred

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0])

In [22]:
#Evaluation metric for the Classification using confusion matrix
from sklearn.metrics import confusion_matrix
conf_mx = confusion_matrix(Y_test,Y_pred)

In [23]:
conf_mx

array([[77,  3],
       [32, 20]])

In [24]:
from sklearn.metrics import classification_report
clf_report = classification_report(Y_test,Y_pred)

In [25]:
#printing the classification report
print(clf_report)

              precision    recall  f1-score   support

           0       0.71      0.96      0.81        80
           1       0.87      0.38      0.53        52

    accuracy                           0.73       132
   macro avg       0.79      0.67      0.67       132
weighted avg       0.77      0.73      0.70       132



In [26]:
conf_mx

array([[77,  3],
       [32, 20]])

In [27]:
clf_model.predict([[40,300,1]])

/home/had/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array([0])