In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv("CKD.csv")

In [3]:
dataset

age         bp sg   al   su     rbc        pc         pcc  \
0     2.000000  76.459948  c  3.0  0.0  normal  abnormal  notpresent   
1     3.000000  76.459948  c  2.0  0.0  normal    normal  notpresent   
2     4.000000  76.459948  a  1.0  0.0  normal    normal  notpresent   
3     5.000000  76.459948  d  1.0  0.0  normal    normal  notpresent   
4     5.000000  50.000000  c  0.0  0.0  normal    normal  notpresent   
..         ...        ... ..  ...  ...     ...       ...         ...   
394  51.492308  70.000000  a  0.0  0.0  normal    normal  notpresent   
395  51.492308  70.000000  c  0.0  2.0  normal    normal  notpresent   
396  51.492308  70.000000  c  3.0  0.0  normal    normal  notpresent   
397  51.492308  90.000000  a  0.0  0.0  normal    normal  notpresent   
398  51.492308  80.000000  a  0.0  0.0  normal    normal  notpresent   

             ba         bgr  ...        pcv            wc        rc  htn   dm  \
0    notpresent  148.112676  ...  38.868902   8408.191126  4.705597   no   no   
1    notpresent  148.112676  ...  34.000000  12300.000000  4.705597   no   no   
2    notpresent   99.000000  ...  34.000000   8408.191126  4.705597   no   no   
3    notpresent  148.112676  ...  38.868902   8408.191126  4.705597   no   no   
4    notpresent  148.112676  ...  36.000000  12400.000000  4.705597   no   no   
..          ...         ...  ...        ...           ...       ...  ...  ...   
394  notpresent  219.000000  ...  37.000000   9800.000000  4.400000   no   no   
395  notpresent  220.000000  ...  27.000000   8408.191126  4.705597  yes  yes   
396  notpresent  110.000000  ...  26.000000   9200.000000  3.400000  yes  yes   
397  notpresent  207.000000  ...  38.868902   8408.191126  4.705597  yes  yes   
398  notpresent  100.000000  ...  53.000000   8500.000000  4.900000   no   no   

     cad  appet    pe  ane classification  
0     no    yes   yes   no            yes  
1     no    yes  poor   no            yes  
2     no    yes  poor   no            yes  
3     no    yes  poor  yes            yes  
4     no    yes  poor   no            yes  
..   ...    ...   ...  ...            ...  
394   no    yes  poor   no            yes  
395   no    yes  poor  yes            yes  
396   no   poor  poor   no            yes  
397   no    yes  poor  yes            yes  
398   no    yes  poor   no             no  

[399 rows x 25 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset

age         bp   al   su         bgr          bu        sc  \
0     2.000000  76.459948  3.0  0.0  148.112676   57.482105  3.077356   
1     3.000000  76.459948  2.0  0.0  148.112676   22.000000  0.700000   
2     4.000000  76.459948  1.0  0.0   99.000000   23.000000  0.600000   
3     5.000000  76.459948  1.0  0.0  148.112676   16.000000  0.700000   
4     5.000000  50.000000  0.0  0.0  148.112676   25.000000  0.600000   
..         ...        ...  ...  ...         ...         ...       ...   
394  51.492308  70.000000  0.0  0.0  219.000000   36.000000  1.300000   
395  51.492308  70.000000  0.0  2.0  220.000000   68.000000  2.800000   
396  51.492308  70.000000  3.0  0.0  110.000000  115.000000  6.000000   
397  51.492308  90.000000  0.0  0.0  207.000000   80.000000  6.800000   
398  51.492308  80.000000  0.0  0.0  100.000000   49.000000  1.000000   

            sod       pot       hrmo  ...  pc_normal  pcc_present  ba_present  \
0    137.528754  4.627244  12.518156  ...          0            0           0   
1    137.528754  4.627244  10.700000  ...          1            0           0   
2    138.000000  4.400000  12.000000  ...          1            0           0   
3    138.000000  3.200000   8.100000  ...          1            0           0   
4    137.528754  4.627244  11.800000  ...          1            0           0   
..          ...       ...        ...  ...        ...          ...         ...   
394  139.000000  3.700000  12.500000  ...          1            0           0   
395  137.528754  4.627244   8.700000  ...          1            0           0   
396  134.000000  2.700000   9.100000  ...          1            0           0   
397  142.000000  5.500000   8.500000  ...          1            0           0   
398  140.000000  5.000000  16.300000  ...          1            0           0   

     htn_yes  dm_yes  cad_yes  appet_yes  pe_yes  ane_yes  classification_yes  
0          0       0        0          1       1        0                   1  
1          0       0        0          1       0        0                   1  
2          0       0        0          1       0        0                   1  
3          0       0        0          1       0        1                   1  
4          0       0        0          1       0        0                   1  
..       ...     ...      ...        ...     ...      ...                 ...  
394        0       0        0          1       0        0                   1  
395        1       1        0          1       0        1                   1  
396        1       1        0          0       0        0                   1  
397        1       1        0          1       0        1                   1  
398        0       0        0          1       0        0                   0  

[399 rows x 28 columns]

In [6]:
#renaming the columns
dataset.rename(columns={"rbc_normal":"rbc","pc_normal":"pc","pcc_present":"pcc","ba_present":"ba","htn_yes":"htn",
                        "dm_yes":"dm","cad_yes":"cad","appet_yes":"appet","pe_yes":"pe",
                        "ane_yes":"ane","classification_yes":"classification"},inplace=True)

In [7]:
#printing the updated dataset
dataset

age         bp   al   su         bgr          bu        sc  \
0     2.000000  76.459948  3.0  0.0  148.112676   57.482105  3.077356   
1     3.000000  76.459948  2.0  0.0  148.112676   22.000000  0.700000   
2     4.000000  76.459948  1.0  0.0   99.000000   23.000000  0.600000   
3     5.000000  76.459948  1.0  0.0  148.112676   16.000000  0.700000   
4     5.000000  50.000000  0.0  0.0  148.112676   25.000000  0.600000   
..         ...        ...  ...  ...         ...         ...       ...   
394  51.492308  70.000000  0.0  0.0  219.000000   36.000000  1.300000   
395  51.492308  70.000000  0.0  2.0  220.000000   68.000000  2.800000   
396  51.492308  70.000000  3.0  0.0  110.000000  115.000000  6.000000   
397  51.492308  90.000000  0.0  0.0  207.000000   80.000000  6.800000   
398  51.492308  80.000000  0.0  0.0  100.000000   49.000000  1.000000   

            sod       pot       hrmo  ...  pc  pcc  ba  htn  dm  cad  appet  \
0    137.528754  4.627244  12.518156  ...   0    0   0    0   0    0      1   
1    137.528754  4.627244  10.700000  ...   1    0   0    0   0    0      1   
2    138.000000  4.400000  12.000000  ...   1    0   0    0   0    0      1   
3    138.000000  3.200000   8.100000  ...   1    0   0    0   0    0      1   
4    137.528754  4.627244  11.800000  ...   1    0   0    0   0    0      1   
..          ...       ...        ...  ...  ..  ...  ..  ...  ..  ...    ...   
394  139.000000  3.700000  12.500000  ...   1    0   0    0   0    0      1   
395  137.528754  4.627244   8.700000  ...   1    0   0    1   1    0      1   
396  134.000000  2.700000   9.100000  ...   1    0   0    1   1    0      0   
397  142.000000  5.500000   8.500000  ...   1    0   0    1   1    0      1   
398  140.000000  5.000000  16.300000  ...   1    0   0    0   0    0      1   

     pe  ane  classification  
0     1    0               1  
1     0    0               1  
2     0    0               1  
3     0    1               1  
4     0    0               1  
..   ..  ...             ...  
394   0    0               1  
395   0    1               1  
396   0    0               1  
397   0    1               1  
398   0    0               0  

[399 rows x 28 columns]

In [8]:
#printing the columns
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc', 'pc', 'pcc', 'ba',
       'htn', 'dm', 'cad', 'appet', 'pe', 'ane', 'classification'],
      dtype='object')

In [9]:
dataset["classification"].value_counts()

1    249
0    150
Name: classification, dtype: int64

In [10]:
#separating the feature and target values.
feature = dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc', 'pc', 'pcc', 'ba',
       'htn', 'dm', 'cad', 'appet', 'pe', 'ane']]
target = dataset[['classification']]

In [11]:
#printing the no of columns and rows of input and output 
feature.shape,target.shape

((399, 27), (399, 1))

In [12]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(feature, target, test_size = 0.33, random_state = 42)

In [13]:
(X_train,X_test),(X_train.shape,X_test.shape)

((      age    bp   al   su         bgr    bu   sc         sod       pot  \
  324  68.0  80.0  3.0  2.0  157.000000  90.0  4.1  130.000000  6.400000   
  176  52.0  80.0  0.0  0.0  125.000000  22.0  1.2  139.000000  4.600000   
  119  45.0  70.0  2.0  0.0  117.000000  52.0  2.2  136.000000  3.800000   
  192  54.0  90.0  1.0  0.0  150.000000  18.0  1.2  140.000000  4.200000   
  202  55.0  80.0  0.0  0.0  130.000000  50.0  1.2  147.000000  5.000000   
  ..    ...   ...  ...  ...         ...   ...  ...         ...       ...   
  71   35.0  80.0  0.0  0.0  104.000000  31.0  1.2  135.000000  5.000000   
  106  43.0  60.0  0.0  0.0  108.000000  25.0  1.0  144.000000  5.000000   
  270  62.0  90.0  1.0  0.0   94.000000  25.0  1.1  131.000000  3.700000   
  348  71.0  90.0  0.0  3.0  303.000000  30.0  1.3  136.000000  4.100000   
  102  43.0  80.0  2.0  3.0  148.112676  30.0  1.1  137.528754  4.627244   
  
            hrmo  ...  rbc  pc  pcc  ba  htn  dm  cad  appet  pe  ane  
  324   5.600

In [14]:
(Y_train,Y_test),(Y_train.shape,Y_test.shape)

((     classification
  324               1
  176               0
  119               1
  192               1
  202               0
  ..              ...
  71                0
  106               0
  270               1
  348               1
  102               1
  
  [267 rows x 1 columns],
       classification
  198               1
  349               0
  33                0
  208               1
  93                0
  ..              ...
  393               1
  380               1
  384               0
  310               1
  145               1
  
  [132 rows x 1 columns]),
 ((267, 1), (132, 1)))

In [15]:
#Model creation & Training phase
from sklearn.naive_bayes import MultinomialNB
MNB_classif = MultinomialNB()
MNB_classif.fit(X_train, Y_train)

#Testing phase
Y_pred = MNB_classif.predict(X_test)


#Scoring phase for decide best model
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, Y_pred)

from sklearn.metrics import classification_report
clf_report = classification_report(Y_test, Y_pred)              

print(clf_report)

print(cm)

              precision    recall  f1-score   support

           0       0.71      0.96      0.82        53
           1       0.97      0.73      0.83        79

    accuracy                           0.83       132
   macro avg       0.84      0.85      0.83       132
weighted avg       0.86      0.83      0.83       132

[[51  2]
 [21 58]]


/home/had/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [16]:
#support values [53 79] denotes the Y_test which is 132(rows) x 1(cols) - Accuracy is 93 for MNB

In [17]:
#Model creation & Training phase
from sklearn.naive_bayes import BernoulliNB
BNB_classif = BernoulliNB()
BNB_classif.fit(X_train, Y_train)

#Testing phase
Y_pred = BNB_classif.predict(X_test)


#Scoring phase for decide best model
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, Y_pred)

from sklearn.metrics import classification_report
clf_report = classification_report(Y_test, Y_pred)    

print(clf_report)

print(cm)

              precision    recall  f1-score   support

           0       0.83      0.98      0.90        53
           1       0.99      0.86      0.92        79

    accuracy                           0.91       132
   macro avg       0.91      0.92      0.91       132
weighted avg       0.92      0.91      0.91       132

[[52  1]
 [11 68]]


/home/had/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [18]:
#support values [53 79] denotes the Y_test which is 132(rows) x 1(cols) - Accuracy is .91 for BNB

In [20]:
#MOdel creation and training phase
from sklearn.naive_bayes import ComplementNB
CMNB_classif =ComplementNB()
CMNB_classif .fit(X_train, Y_train)

#Testing phase
Y_pred = CMNB_classif.predict(X_test)

#SCoring phase to choose best model
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, Y_pred)

from sklearn.metrics import classification_report
clf_report = classification_report(Y_test, Y_pred)    

print(clf_report)

print(cm)

              precision    recall  f1-score   support

           0       0.71      0.98      0.83        53
           1       0.98      0.73      0.84        79

    accuracy                           0.83       132
   macro avg       0.85      0.86      0.83       132
weighted avg       0.87      0.83      0.83       132

[[52  1]
 [21 58]]


/home/had/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
